name = "nonogram-lean"
version = "0.1.0"
defaultTargets = ["nonogram"]

[[lean_lib]]
name = "nonoLib"
roots = ["Nonogram"]

[[lean_exe]]
name = "nonogram"
root = "Main"

[[lean_exe]]
name = "nonoBench"
root = "Benchmarks.LineSolver"

[[lean_exe]]
name = "nonoSieve"
root = "Tools.Sieve"
